language: node_js
node_js:
  - "4.4"
branches:
  only:
    - master
before_install:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g resume-cli
install:
  - npm install
script:
  - gulp
  - resume test